// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuTXpM9oxzTr-unpdlhPAX1JBmgDM4v50',
    appId: '1:500882680207:web:b003d39acc622b06dd03fa',
    messagingSenderId: '500882680207',
    projectId: 'file-locker-6812e',
    authDomain: 'file-locker-6812e.firebaseapp.com',
    storageBucket: 'file-locker-6812e.appspot.com',
    measurementId: 'G-Y81PXF5LBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuxmx8knCQCaOqXN6I4IEGc0-JYJGMkpc',
    appId: '1:500882680207:android:7af56d031304b738dd03fa',
    messagingSenderId: '500882680207',
    projectId: 'file-locker-6812e',
    storageBucket: 'file-locker-6812e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJB1uDl5utZnkZ2nZng1Riv1OTZYbpKGU',
    appId: '1:500882680207:ios:d32d6d2e03cc1cd3dd03fa',
    messagingSenderId: '500882680207',
    projectId: 'file-locker-6812e',
    storageBucket: 'file-locker-6812e.appspot.com',
    iosClientId: '500882680207-di4bmihtlnrifi3r79238pchnmrblvam.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeAndLock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJB1uDl5utZnkZ2nZng1Riv1OTZYbpKGU',
    appId: '1:500882680207:ios:d32d6d2e03cc1cd3dd03fa',
    messagingSenderId: '500882680207',
    projectId: 'file-locker-6812e',
    storageBucket: 'file-locker-6812e.appspot.com',
    iosClientId: '500882680207-di4bmihtlnrifi3r79238pchnmrblvam.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeAndLock',
  );
}
